# Generated by Django 3.2.6 on 2021-08-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20210829_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='marks',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='student',
            name='Class',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='School',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
